### ISSUE TITLE
Support of a new encryption method

### ISSUE THREAD

**Issue by aivus** [inwaar/gree-hvac-client#22]
Starting from v1.21 wifi module uses AES GCM instead of ECB

References:
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/pull/165
https://github.com/tomikaa87/gree-remote/pull/64
https://github.com/tomikaa87/gree-remote/issues/52

**Comment by cont1nuity** [comment]
See as well: https://github.com/XHunter74/ioBroker.gree-hvac/pull/29
