### ISSUE TITLE
Emit noPollingResponse event when HVAC doesn't respond on polling

### ISSUE THREAD

**Issue by aivus** [inwaar/gree-hvac-client#4]
Hi

What do you think about adding `noPollingResponse` event (or something similar?) which can be emitted in case when HVAC doesn't respond to the polling request?

For example we have `polling: true` and `pollingInterval: 3000`.
Using `setTimeout` with `pollingInterval*2` we emit `noPollingResponse`.

It allows library users to handle case when polling was not successful and mark device as offline (for example).

Any thoughts about this?

**Comment by inwaar** [comment]
This has to be added since v1.2.3.

An example:
```
client.on('no_response', () => {
    console.log('no response');
});
```

**Comment by aivus** [comment]
Works like a charm. Thanks 💯
